version: '3.3'

services:
    node-app:
        build:
          context: .
          dockerfile: DockerFile
        environment:
            - DATABASE_HOST=db
        depends_on:
            - db
        restart: always
        ports:
            - 3000:3000
    db:
        build: ./mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gov_tec_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root